import cron from "node-cron";
import { publishToInstagram } from "../utils/instagram.js";

cron.schedule("0 */6 * * *", async () => {
  console.log("Auto-post triggered");

  const imageUrl = "YOUR_IMAGE_GENERATOR_OUTPUT";
  const caption = "Auto-generated by 11Eleven";

  await publishToInstagram(imageUrl, caption);
});
